import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const font = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={font.className}>
      <div className="min-h-screen flex flex-col">
        <main className="flex-grow container mx-auto p-4">
          {children}
        </main>
        <footer className="bg-gray-800 text-white p-4 text-center">
          <div className="container mx-auto">
            Project for MMC by Andrei Gherman
          </div>
        </footer>
      </div>
      </body>
      </html>
  );
}
